---
### ---------------------------------------------------------------------------
### QUERY THE HEALTH OF THE WAN LINKS ON A SRX
### ---------------------------------------------------------------------------
- name: Collect stats from the LTE interfaces and return a report to Slack
  hosts: "{{ site_name }}"
  connection: local
  gather_facts: False
  roles:
    - juniper.junos
  tasks:

    - name: get modem wireless network
      juniper_junos_rpc:
        provider: "{{ provider_info }}"
        rpcs: "get-modem-wireless-network"
        format: "json"
        kwargs:
          interface_name: "cl-1/1/0"
      register: get_modem_wireless_network

    - name: create report_modem
      set_fact:
        report_modem: "{{ get_modem_wireless_network | report_modem_wireless_network }}"

    - name: get modem wireless rssi
      juniper_junos_rpc:
        provider: "{{ provider_info }}"
        rpcs: "get-modem-wireless-rssi"
        format: "json"
        kwargs:
          interface_name: cl-1/1/0
      register: get_modem_wireless_rssi

    - name: create report_rssi
      set_fact:
        report_rssi: "{{ get_modem_wireless_rssi | report_modem_wireless_rssi }}"

    - name: report to Slack
      include_role:
        name: slack_wan_health_lte
