---
  ### ---------------------------------------------------------------------------
  ### USES MIST'S API TO UPDATE THE CONFIGURATION OF A MANAGED SWITCH
  ### ---------------------------------------------------------------------------
  - hosts: localhost
    connection: local
    gather_facts: False
    become: False
    roles:
      ### ---------------------------------------------------------------------------
      ### Mist Wireless work  
      ### ---------------------------------------------------------------------------
      - { role: mist_configure_switch }
