---
  ### ---------------------------------------------------------------------------
  ### USES MIST'S API TO UPDATE THE CONFIGURATION OF A MANAGED SWITCH
  ### ---------------------------------------------------------------------------
  - hosts: localhost
    connection: local
    gather_facts: False
    become: False
    tasks:
      ### Configure EX switch  
      - name: Send updated switch configuration
        uri:
          url: "https://{{ mist_wired.base_url }}/sites/{{ mist_wired.id_site }}/devices/{{ mist_wired.id_device }}"
          headers:
            Authorization: "Token {{ mist_wired.api_token }}"
          return_content: yes
          status_code: 200
          method: PUT
          body: "{{ mist_wired_config | to_json }}"
          body_format: json
        register: response

      - debug:
          msg: "{{ response }}"