  
### ---------------------------------------------------------------------------
### ASSIGN SWITCH TO SITE
### ---------------------------------------------------------------------------

- name: "Assign Switch to Site"
  uri:
    url: "https://{{ mist_wired.base_url }}/orgs/{{ mist_wired.id_org }}/inventory"
    method: PUT
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ mist_wired.api_token }}"
    body: "{{ assign_switch }}"
    force_basic_auth: yes
    body_format: json
  register: assign_switch
