### ---------------------------------------------------------------------------
### FORMAT MAC ADDRESSES
### ---------------------------------------------------------------------------
- name: "Format MAC addresses"
  set_fact:
     cleaned_macs: "{{ claimed_switch.json.inventory_added | cleanup_switch_mac }}"
     
- name:
  debug:
    var: cleaned_macs
    
### ---------------------------------------------------------------------------
### BUILD PAYLOAD FOR SITE
### ---------------------------------------------------------------------------
- name: "Create a JSON payload with site details"
  template:
    src: mist_assign_switch.j2
    dest: /var/tmp/mist_assign_switch.json
    mode: 0640
    
- name: "Assign Switch to Site"
  uri:
    url: "https://{{ mist_wired.base_url }}/orgs/{{ mist_wired.id_org }}/inventory"
    headers:
      Authorization: "Token {{ mist_wired.api_token }}"
    return_content: yes
    status_code: "200"
    method: PUT
    body: "{{ lookup('file','/var/tmp/mist_assign_switch.json') }}"
    body_format: json
  register: assign_switch
 
- name:
  debug:
    var: assign_switch

