---
isolate:
    networks:
        - name: Management
          vlan_id: '12'
        - name: Blackhole
          vlan_id: '255'
    port_profiles:
        - name: ap
          port_network: default
          disabled: false
          port_auth: 
          mode: trunk
          stp_edge: true
          isOverrider: true
          networks: []
          all_networks: true
        - name: blackhole
          port_network: Blackhole
          all_networks: false
          port_auth: 
          mode: access
          stp_edge: true
          networks: []
          disabled: true
        - name: uplink
          port_network: default
          disabled: false
          port_auth: 
          mode: trunk
          stp_edge: true
          networks: []
          all_networks: true
    notes: 'under cyber security event'
    managed: true
    ip_config:
        type: dhcp
        network: Management
    role: ''
    port_config:
        - name: ge-0/0/0
          usage: uplink
        - name: ge-0/0/1-9,ge-0/0/11
          usage: blackhole
        - name: ge-0/0/10
          usage: ap
    additional_config_cmds:
        - set system domain-name network.home
        - set system name-server 10.6.6.20
        - set system name-server 10.6.6.21
    name: seattle-sw1
