---
switch:
  additional_config_cmds:
    - set system domain-name network.home
    - set system name-server 10.6.6.20
    - set system name-server 10.6.6.21
  ip_config:
    network: oob
    type: dhcp
  managed: true
  name: seattle-sw1
  networks:
    - name: oob
      vlan_id: '10'
    - name: employee
      vlan_id: '11'
    - name: guest
      vlan_id: '12'
    - name: iot
      vlan_id: '13'
    - name: pci
      vlan_id: '14'
  notes: '20200817-CCR: change port configs'
  port_config:
    - name: 'ge-0/0/1,ge-0/0/11'
      usage: trunk
    - name: 'ge-0/0/2,ge-0/0/4,ge-0/0/6'
      usage: vmware
    - name: ge-0/0/3
      usage: pci
    - name: 'ge-0/0/5,ge-0/0/7'
      usage: iot
    - name: ge-0/0/10
      usage: ap
  port_profiles:
    - name: ap
      port_network: default
      all_networks: true
      disabled: false
      isOverrider: true
      mode: trunk
      networks: []
      port_auth: null
      stp_edge: true
    - name: default
      port_network: guest
      all_networks: false
      disabled: false
      mode: access
      networks: []
      port_auth: null
      stp_edge: true
    - name: employee
      port_network: employee
      all_networks: false
      disabled: false
      mode: access
      networks: []
      port_auth: null
      stp_edge: true
    - name: pci
      port_network: pci
      all_networks: false
      disabled: false
      mode: access
      networks: []
      port_auth: null
      stp_edge: true
    - name: trunk
      port_network: default
      all_networks: true
      disabled: false
      mode: trunk
      networks: []
      port_auth: null
      stp_edge: true
    - name: vmware
      port_network: default
      all_networks: true
      disabled: false
      mode: trunk
      networks: []
      port_auth: null
      stp_edge: true
  role: ''