---
switch:
    networks:
        - name: Employee
          vlan_id: '11'
        - name: Guest
          vlan_id: '12'
        - name: IOT
          vlan_id: '13'
        - name: PCI
          vlan_id: '14'
    port_profiles:
        - name: ap
          port_network: default
          disabled: false
          port_auth: 
          mode: trunk
          stp_edge: true
          isOverrider: true
          networks: []
          all_networks: true
        - name: default
          port_network: Guest
          all_networks: false
          port_auth: 
          mode: access
          stp_edge: true
          networks: []
          disabled: false
        - name: pci
          port_network: PCI
          all_networks: false
          port_auth: 
          mode: access
          stp_edge: true
          networks: []
          disabled: false
        - name: uplink
          port_network: default
          disabled: false
          port_auth: 
          mode: trunk
          stp_edge: true
          networks: []
          all_networks: true
        - name: vmware
          port_network: default
          all_networks: true
          port_auth: 
          mode: trunk
          stp_edge: true
          networks: []
          disabled: false
        - name: employee
          port_network: Employee
          all_networks: false
          port_auth: 
          mode: access
          stp_edge: true
          networks: []
          disabled: false
    notes: ''
    managed: true
    ip_config:
        type: dhcp
        network: Guest
    role: ''
    port_config:
        - name: ge-0/0/0
          usage: uplink
        - name: ge-0/0/2,ge-0/0/4,ge-0/0/6
          usage: vmware
        - name: ge-0/0/8
          usage: pci
        - name: ge-0/0/10
          usage: ap
    additional_config_cmds:
        - set system domain-name network.home
        - set system name-server 10.6.6.20
        - set system name-server 10.6.6.21
    name: Seattle
