---
switch:
  ### # ADDITIONAL CLI COMMANDS FOR OPTIONS NOT IN THE GUI TODAY
  additional_config_cmds:
    - set system domain-name network.home
    - set system name-server 10.6.6.20
    - set system name-server 10.6.6.21

  ### # CONFIGURATION OF THE INBAND MANAGEMENT PORT
  ip_config:
    network: oob
    type: dhcp

  ### # DECLARE IF THE SWITCH IS MANAGED OR NOT
  managed: true

  ### # HOSTNAME
  name: Seattle-sw1

  ### # VLANS
  networks:
    - name: oob
      vlan_id: '10'
    - name: employee
      vlan_id: '11'
    - name: guest
      vlan_id: '12'
    - name: iot
      vlan_id: '13'
    - name: pci
      vlan_id: '14'
  
  ### # ADDITIONAL NOTES
  notes: '20200817-CCR: change port configs'

  ### # PORT CONFIGURATIONS
  port_config:
    - name: 'ge-0/0/1,ge-0/0/11'
      usage: trunk
    - name: 'ge-0/0/2,ge-0/0/4,ge-0/0/6'
      usage: vmware
    - name: ge-0/0/3
      usage: pci
    - name: 'ge-0/0/5,ge-0/0/7'
      usage: iot
    - name: ge-0/0/10
      usage: ap

  ### # GROUP CONFIGURATIONS FOR INTERFACES
  port_profiles:
    ### # ACCESS POINTS
    - name: ap
      port_network: oob
      all_networks: true
      disabled: false
      isOverrider: true
      mode: trunk
      networks: []
      port_auth: null
      stp_edge: true
    
    ### # DEFAULT 
    - name: default
      port_network: guest
      all_networks: false
      disabled: false
      mode: access
      networks: []
      port_auth: null
      stp_edge: true
    
    ### # EMPLOYEE
    - name: employee
      port_network: employee
      all_networks: false
      disabled: false
      mode: access
      networks: []
      port_auth: null
      stp_edge: true
    
    ### # PCI
    - name: pci
      port_network: pci
      all_networks: false
      disabled: false
      mode: access
      networks: []
      port_auth: null
      stp_edge: true
    
    ### # GENERIC TRUNK PORT
    - name: trunk
      port_network: default
      all_networks: true
      disabled: false
      mode: trunk
      networks: []
      port_auth: null
      stp_edge: true
    
    ### # VMWARE SERVERS
    - name: vmware
      port_network: default
      all_networks: true
      disabled: false
      mode: trunk
      networks: []
      port_auth: null
      stp_edge: true
  role: ''