---
config:
  dhcp:
    max_lease_time: 86400
    name_server: 
      primary: "8.8.8.8"
      secondary: "8.8.4.4"
  cpe:
    lan_ports: "ae0"
    wan_link:
      primary:
        local_interface: "ge-0/0/0"
        name: WAN_0
        wan_link_type: MPLS
        access_type: Ethernet
        provider: ISP1
        cost: 800
        mesh_tag: MPLS
      secondary:
        local_interface: "ge-0/0/1"
        name: WAN_1
        wan_link_type: Internet
        access_type: Ethernet
        provider: ISP2
        cost: 800
        mesh_tag: INTERNET
    overlay:
      tunnel_type: GRE_IPSEC
    vpn_name: 
      primary: "{{ tenant_name }}_DefaultVPN"
#     trunk_ports_1: "ge-0/0/1"
#     trunk_ports_2: "ge-0/0/2"
    template_name: "HerndonPOC/POC_Spoke_SRX"
#   switch:
#     template_name: "EX_Single_ZTP"
#     device_role: "LAN_DEVICE_EX"
  site_deployment_capabilities:
    primary: SDWAN
#     secondary: LAN_DEVICE_EX
  ntpserver: "216.239.35.4"
  timezone: "America/Chicago"
  gateway_sites:
    primary: ent-dc1
    secondary: ent-dc2
  hub_sites:
    primary: 
      name: JNPR-US-E-HUB-1
      gw_ip: "67.128.79.33"
    secondary: 
      name: JNPR-US-E-HUB-2
      gw_ip: "67.128.79.37"
  mgmt_prefix: "10.23.23.0/24"
