### ---------------------------------------------------------------------------
### UPDATE TEAM IN SLACK
### ---------------------------------------------------------------------------
- name: "Create a JSON payload with DSL health details"
  template:
    src: "slack_wan_health_{{ detail }}.j2"
    dest: /var/tmp/slack_wan_health.json
    mode: 0640
  run_once: True

- name: "send an update message to team on Slack"
  uri:
    url: "{{ slack.dsl_bot }}"
    method: POST
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
    body: "{{ lookup('file','/var/tmp/slack_wan_health.json') }}"
    force_basic_auth: yes
    body_format: json
  register: slack_message
  run_once: True
