### ---------------------------------------------------------------------------
### BUILD SITE PAYLOAD FOR CSO
### ---------------------------------------------------------------------------
- name: "tranlate YAML to Python dictionary"
  set_fact:
    yaml_to_python: "{{ site_yaml_config | yaml_to_dict }}"

- name: "write the Python dictionary to a local file"
  local_action: 
    module: copy 
    content: "{{ yaml_to_python }}"
    dest: "{{ python_dict_config }}"

# - name: "build the SD-WAN site with custom module"
#   cso_site:
#     site_name: "{{ inventory_hostname }}"
#     config: "{{ site_python_config }}"
#     state: present
#     token: "{{ token }}"

- name: "build the SD-WAN site without custom module"
  uri:
    url: https://contrail-juniper.net/tssm/configure-sites
    method: POST
    headers:
      x-auth-token: "{{ token }}"
    body: "{{ site_python_config }}"
    body_format: json
    status_code: 200
