---
cso_auth_config: "{{ lookup('file','/var/tmp/cso_auth.json') }}"
mist_auth_config: "{{ lookup('file','/var/tmp/mist_auth.json') }}"

site_config: "./host_vars/{{ inventory_hostname }}/all.yml"
site_yaml_config: "{{ lookup('file', site_config) }}"

python_dict_config: "/var/tmp/{{ inventory_hostname }}.py"
site_python_config: "{{ lookup('file', python_dict_config) }}"

site_json: "/var/tmp/{{ inventory_hostname }}.json"

cso_tenant_id: "898312070-3946-40f9-9af7-6a744e78cc34"
