### ---------------------------------------------------------------------------
### RETREIVE A DEVICE'S STAGE 1 CONFIG
### ---------------------------------------------------------------------------
- name: "### SET VARIABLES ###"
  set_fact:
    provider_info:
      host: 10.6.5.195
      user: root
      passwd: juniper123
      port: 830

- juniper_junos_config:
    load: 'merge'
    host: "{{ provider_info.host }}"
    user: "{{ provider_info.user }}"
    passwd: "{{ provider_info.passwd }}"
    # ssh_private_key_file: "{{ provider_info.ssh_private_key_file }}"
    format: text
    lines: "{{ config }}"
    timeout: 240
  register: result
  ignore_errors: yes

- name: "### PRINT THE RESULT TO CONSOLE ###"
  debug:
    var: result.diff_lines
  when: result.diff_lines is defined

