  
### ---------------------------------------------------------------------------
### CLAIM SWITCH TO MIST
### ---------------------------------------------------------------------------
- name: "Claim switch to Mist"
  uri:
    url: "https://{{ mist_wired.base_url }}/orgs/{{ mist_wired.id_org }}/inventory"
    method: POST
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
      Authorization: "Token {{ mist_wired.api_token }}"
    body: 
      - "{{ claim_code }}"
    force_basic_auth: yes
    body_format: json
  register: claimed_switch
       
- name: "Claimed Switch"
  debug:
    var: "{{ claimed_switch.json.inventory_added[0] }}"

- name: "Run cleanup function on switch_name variable"
  set_fact:
    cleaned_switch_name: "{{ claimed_switch.json.inventory_added[0] }}"
  run_once: True
