### ---------------------------------------------------------------------------
### BUILD AUTHENTICATION PAYLOAD FOR CSO
### ---------------------------------------------------------------------------
- name: "Create a JSON payload with username and password for our auth task"
  template:
    src: mist_auth.j2
    dest: "{{ mist_auth_config }}"
    mode: 0640
  run_once: True

### ---------------------------------------------------------------------------
### RECEIVE AUTH TOKEN FROM CSO
### ---------------------------------------------------------------------------
- name: "Login to Mist and retrieve AUTH token"
  uri:
    url: "{{ mist.baseurl }}/v1/login"
    method: POST
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
    username: "{{ mist.username }}"
    password: "{{ mist.password }}"
    body: "{{ lookup('file','{{ mist_auth_config }}') }}"
    force_basic_auth: yes
    body_format: json
  register: login
  run_once: True

- name: "Setting the cookies based on the headers received"
  set_fact:
    mist_csrftoken: "{{ login.cookies.csrftoken }}"
    mist_sessionid: "{{ login.cookies.sessionid }}"
  run_once: True
