---
input:
  tenant_name: "{{ tenant_name }}"
  deployment_scenario: managed_wan_v2
  site:
    - site_name: "{{ cleaned_site_name }}"
      site_basic_properties:
        site_name: "{{ cleaned_site_name }}"
        site_group: []
        site_role: SPOKE
        dvpn_params:
          create_dvpn_threshold: "5"
          delete_dvpn_threshold: "2"          
 ######################################################
 Update Site Address
 ######################################################
#         site_address:
#           street: "{{ site_data.street_address }}"
#           city: "{{ site_data.city }}"
#           state: "{{ site_data.state }}"
#           # zip_code: "{{ site_data.zip_code }}"
#           country: "{{ site_data.country }}"
        site_contact:
          contact_name: "{{ site_data.contact_name }}"
          email_address: "{{ site_data.contact_email }}"
          phone_number: "{{ site_data.contact_phone }}"
        network_seg: true
        cloud_service: EDGE
        site_type: on_premise
        topology: mesh
        sla_mgmt: FINE
        device_template:
          - template_name: "{{ config.cpe.template_name }}"
            device_name: "{{ cleaned_site_name }}"
            wan_link_info:
              - wan_link: "{{ config.cpe.wan_link.primary.name }}"
                wan_link_type: "{{ config.cpe.wan_link.primary.wan_link_type }}"
                cost_currency: USD
                access_type: "{{ config.cpe.wan_link.primary.access_type }}"
                local_breakout_enabled: false
                provider: "{{ config.cpe.wan_link.primary.provider }}"
                cost: "{{ config.cpe.wan_link.primary.cost }}"
                default_link: false
                backup_link: false
                subscribed_bandwidth: 800
                enable_pppoe: false
            lan_segment:
              # ### DATA VLAN
              - lan_segment_name: "{{ site_prefixes.data.name }}"
                lan_segment_type: direct
                vlan: "{{ site_prefixes.data.vid | int }}"
                department: "{{ site_prefixes.data.vrf }}"
                ip_prefix: "{{ device_prefixes.data.address }}"
                dhcp: true
                additional_config:
                  dhcp:
                    range_low: "{{ site_prefixes.data.dhcp_low }}"
                    range_high: "{{ site_prefixes.data.dhcp_high }}"
                    max_lease_time: 86400
                    name_server:
                      - "{{ config.dhcp.name_server.primary }}"
                      - "{{ config.dhcp.name_server.secondary }}"
                    subnet: "{{ device_prefixes.data.address }}"
                lan_ports:
                  - "{{ config.cpe.lan_ports }}"
              # ### VOICE VLAN
              - lan_segment_name: "{{ site_prefixes.voice.name }}"
                lan_segment_type: direct
                vlan: "{{ site_prefixes.voice.vid | int }}"
                department: "{{ site_prefixes.voice.vrf }}"
                ip_prefix: "{{ device_prefixes.voice.address }}"
                dhcp: true
                additional_config:
                  dhcp:
                    range_low: "{{ site_prefixes.voice.dhcp_low }}"
                    range_high: "{{ site_prefixes.voice.dhcp_high }}"
                    max_lease_time: 86400
                    name_server:
                      - "{{ config.dhcp.name_server.primary }}"
                      - "{{ config.dhcp.name_server.secondary }}"
                    subnet: "{{ device_prefixes.voice.address }}"
                lan_ports:
                  - "{{ config.cpe.lan_ports }}"
              # ### IOT VLAN
              - lan_segment_name: "{{ site_prefixes.iot.name }}"
                lan_segment_type: direct
                vlan: "{{ site_prefixes.iot.vid | int }}"
                department: "{{ site_prefixes.iot.vrf }}"
                ip_prefix: "{{ device_prefixes.iot.address }}"
                dhcp: true
                additional_config:
                  dhcp:
                    range_low: "{{ site_prefixes.iot.dhcp_low }}"
                    range_high: "{{ site_prefixes.iot.dhcp_high }}"
                    max_lease_time: 86400
                    name_server:
                      - "{{ config.dhcp.name_server.primary }}"
                      - "{{ config.dhcp.name_server.secondary }}"
                    subnet: "{{ device_prefixes.iot.address }}"
                lan_ports:
                  - "{{ config.cpe.lan_ports }}"
              # ### PCI VLAN
              - lan_segment_name: pci
                lan_segment_type: direct
                vlan: "{{ site_prefixes.pci.vid | int }}"
                department: "{{ site_prefixes.pci.vrf }}"
                ip_prefix: "{{ device_prefixes.pci.address }}"
                dhcp: true
                additional_config:
                  dhcp:
                    range_low: "{{ site_prefixes.pci.dhcp_low }}"
                    range_high: "{{ site_prefixes.pci.dhcp_high }}"
                    max_lease_time: 86400
                    name_server:
                      - "{{ config.dhcp.name_server.primary }}"
                      - "{{ config.dhcp.name_server.secondary }}"
                    subnet: "{{ device_prefixes.pci.address }}"
                lan_ports:
                  - "{{ config.cpe.lan_ports }}"
        site_deployment_capabilities:
          - "{{ config.site_deployment_capabilities.primary }}"
      properties:
        property:
          - name: site_advanced_config
            value:
              nameserver:
                - "{{ config.dhcp.name_server.primary }}"
                - "{{ config.dhcp.name_server.secondary }}"
              ntpserver: "{{ config.ntpserver }}"
              timezone: "{{ config.timezone }}"
      on_premise_site_info:
        site_role: spoke
        ha_info:
          ha_topology: STANDALONE
        device:
          - device_family: "{{ config.cpe.device_family }}"
            device_name: "{{ cleaned_site_name }}"
            device_template: "{{ config.cpe.template_name }}"
            device_details:
              serial_number: "{{ site_devices.cpe.serial }}"
              auto_activate: true
              boot_image: ""
            oam_traffic: {}
            wan_link:
              - wan_link_name: "{{ config.cpe.wan_link.primary.name }}"
                local_interface: "{{ config.cpe.wan_link.primary.local_interface }}"
                wan_link_type: "{{ config.cpe.wan_link.primary.wan_link_type }}"
                access_type: "{{ config.cpe.wan_link.primary.access_type }}"
                address_assignment: DHCP
                used_for_meshing: true
                mesh_overlay_link_type: GRE_IPSEC
                mesh_tag:
                  - "{{ config.cpe.wan_link.primary.mesh_tag }}"
                used_for_oam: true
                connect_to_hubs: true
                overlay_tunnel:
                  - tunnel_id: 0
                    tunnel_endpoint_role: SPOKE
                    vpn_name: "{{ config.cpe.vpn_name.primary }}"
                    tunnel_type: "{{ config.cpe.overlay.tunnel_type }}"
                    peer_info:
                      peer_device: "{{ config.hub_sites.primary.name }}"
                      interface_name: WAN_0
                      internet_gw_ip: "{{ config.hub_sites.primary.gw_ip }}"
                  - tunnel_id: 1
                    tunnel_endpoint_role: SPOKE
                    vpn_name: "{{ config.cpe.vpn_name.primary }}"
                    tunnel_type: "{{ config.cpe.overlay.tunnel_type }}"
                    peer_info:
                      peer_device: "{{ config.hub_sites.secondary.name }}"
                      interface_name: WAN_0
                      internet_gw_ip: "{{ config.hub_sites.secondary.gw_ip }}"
                traffic_type: DATA_ONLY
                backup_link: false
                default_link: false
                vpn:
                  - vpn_name: "{{ config.cpe.vpn_name.primary }}"
            device_role: SDWAN
        hub_sites:
          - hub_role: PRIMARY
            hub_name: "{{ config.hub_sites.primary.name }}"
          - hub_role: SECONDARY
            hub_name: "{{ config.hub_sites.secondary.name }}"
        region: regional
