### ---------------------------------------------------------------------------
### UPDATE TEAM IN SLACK
### ---------------------------------------------------------------------------
- name: "Run cleanup function on site_name variable"
  set_fact:
    cleaned_site_name: "{{ site_name | snow_cleanup_site_name }}"
  run_once: True

- name: "Create a JSON payload with CSO site details"
  template:
    src: cso_site_slack_message.j2
    dest: /var/tmp/cso_site_slack_message.json
    mode: 0640
  run_once: True

- name: "send an update message to team on Slack"
  uri:
    url: "{{ slack.baseurl }}"
    method: POST
    return_content: yes
    status_code: "200"
    headers:
      Content-Type: "application/json"
    body: "{{ lookup('file','/var/tmp/cso_site_slack_message.json') }}"
    force_basic_auth: yes
    body_format: json
  register: slack_message
  run_once: True
